function SetColorScheme(color)
	color = color or "rose-pine"
	vim.cmd.colorscheme(color)

	vim.api.nvim_set_hl(0, "Normal", { bg = "#1A1A1A" })
	vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#1A1A1A" })

    vim.api.nvim_set_hl(0, "Directory", { fg = "#A9B7C6" }) 
    vim.api.nvim_set_hl(0, "Todo", { fg = "#A8A031" }) 
    vim.api.nvim_set_hl(0, "String", { fg = "#6A8759" }) 
    vim.api.nvim_set_hl(0, "Constant", { fg = "#9876AA" }) 
    vim.api.nvim_set_hl(0, "Character", { fg = "#6A8759" }) 
    vim.api.nvim_set_hl(0, "Number", { fg = "#638DAC" }) 
    vim.api.nvim_set_hl(0, "Boolean", { fg = "#466B8B" }) 
    vim.api.nvim_set_hl(0, "Float", { fg = "#638DAC" }) 
    vim.api.nvim_set_hl(0, "Function", { fg = "#FFC66D" }) 
    vim.api.nvim_set_hl(0, "Identifier", { fg = "#CC7832" }) 
    vim.api.nvim_set_hl(0, "Operator", { fg = "#BCBEC4" }) 
    vim.api.nvim_set_hl(0, "Keyword", { fg = "#CF8E6D" }) 
    vim.api.nvim_set_hl(0, "Exception", { fg = "#FF6600" }) 
    vim.api.nvim_set_hl(0, "Include", { fg = "#CC7832" }) 
    vim.api.nvim_set_hl(0, "Define", { fg = "#CC7832" }) 
    vim.api.nvim_set_hl(0, "Macro", { fg = "#57AAF7" }) 
    vim.api.nvim_set_hl(0, "StorageClass", { fg = "#CC7832" }) 
    vim.api.nvim_set_hl(0, "Type", { fg = "#417D49" }) 
    vim.api.nvim_set_hl(0, "Structure", { fg = "#84A889" }) 
    vim.api.nvim_set_hl(0, "Special", { fg = "#FF6600" }) 

    vim.api.nvim_set_hl(0, "Delimiter", { fg = "#BCBEC4" }) 
    vim.api.nvim_set_hl(0, "Comment", { fg = "#7A7E85" }) 

    vim.api.nvim_set_hl(0, "@constant", { fg = "#FFBDBD" }) 
    vim.api.nvim_set_hl(0, "@constant.builtin", { fg = "#656486" }) 
    vim.api.nvim_set_hl(0, "@constructor", { fg = "#466B8B" }) 
    vim.api.nvim_set_hl(0, "@field", { fg = "#916DA5" }) 
    vim.api.nvim_set_hl(0, "@function.builtin", { fg = "#FFC66D" }) 
    vim.api.nvim_set_hl(0, "@function.macro", { fg = "#57AAF7" }) 
    vim.api.nvim_set_hl(0, "@interface", { fg = "#07815d" }) 
    vim.api.nvim_set_hl(0, "@lsp.type.class", { fg = "#A8A031" }) 
    vim.api.nvim_set_hl(0, "@lsp.type.enum", { fg = "#BDADCD" }) 
    vim.api.nvim_set_hl(0, "@lsp.type.enumMember", { fg = "#865497" }) 
    vim.api.nvim_set_hl(0, "@lsp.type.interface", { fg = "#07815d" }) 
    vim.api.nvim_set_hl(0, "@lsp.type.parameter", { fg = "#FCFCFC" }) 
    vim.api.nvim_set_hl(0, "@lsp.type.typeParameter", { fg = "#20999D" }) 
    vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", { fg = "#FFC66D" }) 
    vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", { fg = "#656486" }) 
    vim.api.nvim_set_hl(0, "@method.call", { fg = "#FFC66D" }) 
    vim.api.nvim_set_hl(0, "@namespace", { fg = "#656486" }) 
    vim.api.nvim_set_hl(0, "@parameter", { fg = "#BCBEC4" }) 
    vim.api.nvim_set_hl(0, "@property", { fg = "#916DA5" }) 
    vim.api.nvim_set_hl(0, "@regexp", { fg = "#42C3D4" }) 
    vim.api.nvim_set_hl(0, "@storageclass.lifetime", { fg = "#507874" }) 
    vim.api.nvim_set_hl(0, "@string.escape", { fg = "#FF6600" }) 
    vim.api.nvim_set_hl(0, "@tag", { fg = "#7D5E5E" }) 
    vim.api.nvim_set_hl(0, "@tag.attribute", { fg = "#BCBEC4" }) 
    vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = "#D5B778" }) 
    vim.api.nvim_set_hl(0, "@text.environment.name", { fg = "#20999D" }) 
    vim.api.nvim_set_hl(0, "@type", { fg = "#CC7832" }) 
    vim.api.nvim_set_hl(0, "@type.builtin", { fg = "#466B8B" }) 
    vim.api.nvim_set_hl(0, "@type.qualifier", { fg = "#CC7832" }) 
    vim.api.nvim_set_hl(0, "@variable", { fg = "#FFBDBD" }) 
    vim.api.nvim_set_hl(0, "@variable.builtin", { fg = "#CC7832" }) 
end

SetColorScheme()
